package de.croesch.weekly.data.type.period;

import java.time.LocalDate;
import org.assertj.core.api.AbstractAssert;


/**
 * {@link Week} specific assertions - Generated by CustomAssertionGenerator.
 */
public class WeekAssert extends AbstractAssert<WeekAssert, Week> {

  /**
   * Creates a new <code>{@link WeekAssert}</code> to make assertions on actual Week.
   * @param actual the Week we want to make assertions on.
   */
  public WeekAssert(Week actual) {
    super(actual, WeekAssert.class);
  }

  /**
   * An entry point for WeekAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeek)</code> and get specific assertion with code completion.
   * @param actual the Week we want to make assertions on.
   * @return a new <code>{@link WeekAssert}</code>
   */
  public static WeekAssert assertThat(Week actual) {
    return new WeekAssert(actual);
  }

  /**
   * Verifies that the actual Week's begin is equal to the given one.
   * @param begin the given begin to compare the actual Week's begin to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Week's begin is not equal to the given one.
   */
  public WeekAssert hasBegin(LocalDate begin) {
    // check that actual Week we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected begin of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    LocalDate actualBegin = actual.getBegin();
    if (!org.assertj.core.util.Objects.areEqual(actualBegin, begin)) {
      failWithMessage(assertjErrorMessage, actual, begin, actualBegin);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Week's end is equal to the given one.
   * @param end the given end to compare the actual Week's end to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Week's end is not equal to the given one.
   */
  public WeekAssert hasEnd(LocalDate end) {
    // check that actual Week we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected end of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    LocalDate actualEnd = actual.getEnd();
    if (!org.assertj.core.util.Objects.areEqual(actualEnd, end)) {
      failWithMessage(assertjErrorMessage, actual, end, actualEnd);
    }

    // return the current assertion for method chaining
    return this;
  }

}
