package de.croesch.weekly.data.type.period;

import java.time.LocalDate;
import org.assertj.core.api.AbstractAssert;


/**
 * {@link Year} specific assertions - Generated by CustomAssertionGenerator.
 */
public class YearAssert extends AbstractAssert<YearAssert, Year> {

  /**
   * Creates a new <code>{@link YearAssert}</code> to make assertions on actual Year.
   * @param actual the Year we want to make assertions on.
   */
  public YearAssert(Year actual) {
    super(actual, YearAssert.class);
  }

  /**
   * An entry point for YearAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myYear)</code> and get specific assertion with code completion.
   * @param actual the Year we want to make assertions on.
   * @return a new <code>{@link YearAssert}</code>
   */
  public static YearAssert assertThat(Year actual) {
    return new YearAssert(actual);
  }

  /**
   * Verifies that the actual Year's begin is equal to the given one.
   * @param begin the given begin to compare the actual Year's begin to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Year's begin is not equal to the given one.
   */
  public YearAssert hasBegin(LocalDate begin) {
    // check that actual Year we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected begin of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    LocalDate actualBegin = actual.getBegin();
    if (!org.assertj.core.util.Objects.areEqual(actualBegin, begin)) {
      failWithMessage(assertjErrorMessage, actual, begin, actualBegin);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Year's end is equal to the given one.
   * @param end the given end to compare the actual Year's end to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Year's end is not equal to the given one.
   */
  public YearAssert hasEnd(LocalDate end) {
    // check that actual Year we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected end of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    LocalDate actualEnd = actual.getEnd();
    if (!org.assertj.core.util.Objects.areEqual(actualEnd, end)) {
      failWithMessage(assertjErrorMessage, actual, end, actualEnd);
    }

    // return the current assertion for method chaining
    return this;
  }

}
